In [29]:
import numpy as np

In [30]:
score = [12, 13, 7, 5, 21]
print(score)

scoreArray = np.array(score)
print(scoreArray)

size = np.size(scoreArray)
shape = np.shape(scoreArray)
print(f'The size of the array is: {size}')
print(f'The shape of the array is: {shape}')

[12, 13, 7, 5, 21]
[12 13  7  5 21]
The size of the array is: 5
The shape of the array is: (5,)


In [36]:
ages = [45,65,34,85,74,98,57,40,20,18]
weights = [83,70,80,90,92,93,105,69,88,87]

people = np.array([ages,weights])
print(people)

print(f'The size of the array is: {np.size(people)}')
print(f'The shape of the array is: {np.shape(people)}')

print(people.reshape(4,5, order='C'))


[[ 45  65  34  85  74  98  57  40  20  18]
 [ 83  70  80  90  92  93 105  69  88  87]]
The size of the array is: 20
The shape of the array is: (2, 10)
[[ 45  65  34  85  74]
 [ 98  57  40  20  18]
 [ 83  70  80  90  92]
 [ 93 105  69  88  87]]


In [37]:
zeroArray = np.zeros(10)
print(zeroArray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [38]:
print(np.repeat(3,20))

[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]


In [40]:
print(np.eye(10))

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [73]:
empt = np.empty((5,5),dtype=int)
print(f'Empty 2D NumPy array:\n{empt}')

Empty 2D NumPy array:
[[3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]
 [3 3 3 3 3]]


In [50]:
fll = np.full([5,4],3,dtype=int)
print(f'Empty 2D NumPy array:\n{fll}')

Empty 2D NumPy array:
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
