In [13]:
import numpy as np

In [14]:
ages_list = [10, 5, 8, 32, 65 ,43, 90, 100]
ages = np.array([ages_list])
ages = ages.reshape(2, 4)
print(ages)
print ("Size:\t", ages.size) # Total number of entries
print ("Shape:\t", ages.shape) # the number of rows and columns
print ("Data Type:\t", ages.dtype)

[[ 10   5   8  32]
 [ 65  43  90 100]]
Size:	 8
Shape:	 (2, 4)
Data Type:	 int32


### Exercise
1)  Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]
2)  Generate a matrix (2D numpy array) of the vaues:
        (1 2 4)
    A = (2 3 0)
        (0 5 1)
    - Change the dimensions of this array to another permitted shape
<p>

3)  Run the below code and attempt to reshape the data array to the correct format:
    * ```c1 = np.random.randint(0,110,50)```
    * ```c2 = np.random.rand(50)```
    * ```c3 = np.random.choice(['french', 'english'], 50)```
    * ```data = np.column_stack((c1, c2, c3)).flatten()```

In [15]:
c1 = np.random.randint(0,110,50)
c2 = np.random.rand(50)
c3 = np.random.choice(['french', 'english'], 50)
data = np.column_stack((c1, c2, c3)).flatten()

exe1 = np.array([7, 9, 65, 33, 85, 99])
print(exe1)


[ 7  9 65 33 85 99]


In [16]:

exe2 = np.array(
    [[1, 2, 4,],
    [2, 3, 0],
    [0, 5, 1]]
)
print(exe2)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [17]:
exe2 = exe2.reshape(9,1)
print(exe2)

print(data.reshape(int(data.size/3),3))

[[1]
 [2]
 [4]
 [2]
 [3]
 [0]
 [0]
 [5]
 [1]]
[['39' '0.42129246286726196' 'french']
 ['89' '0.24202428838451207' 'french']
 ['39' '0.2971096434231859' 'french']
 ['35' '0.5718282024444041' 'english']
 ['3' '0.5375401568840038' 'english']
 ['83' '0.28972933935913725' 'french']
 ['14' '0.5926336100607945' 'english']
 ['28' '0.44999135859688466' 'english']
 ['56' '0.9804099125208456' 'english']
 ['31' '0.871683427055945' 'english']
 ['46' '0.9732672590300941' 'french']
 ['40' '0.991448992687789' 'french']
 ['54' '0.2044987565514097' 'english']
 ['72' '0.6040779864635013' 'french']
 ['48' '0.11146468896098849' 'english']
 ['22' '0.5388701330707936' 'english']
 ['85' '0.43781248871444356' 'french']
 ['1' '0.7916343717106081' 'english']
 ['65' '0.13244213134720717' 'english']
 ['36' '0.9915666346904933' 'english']
 ['83' '0.04085180783788134' 'english']
 ['95' '0.5074987241131355' 'english']
 ['59' '0.2628705843609025' 'french']
 ['41' '0.7037217356642361' 'english']
 ['0' '0.13305603979714

In [18]:
# numpy.arange() stores beginnning value, ending value, and step only.
print(np.arange(0,55,5)) 

#numpy.linspace() gives you linear data points on a line
print(np.linspace(0, 100, 25))

#numpy.repeat
print(np.repeat(2,10))

[ 0  5 10 15 20 25 30 35 40 45 50]
[  0.           4.16666667   8.33333333  12.5         16.66666667
  20.83333333  25.          29.16666667  33.33333333  37.5
  41.66666667  45.83333333  50.          54.16666667  58.33333333
  62.5         66.66666667  70.83333333  75.          79.16666667
  83.33333333  87.5         91.66666667  95.83333333 100.        ]
[2 2 2 2 2 2 2 2 2 2]


In [19]:

identityMatrix = np.eye(3)
print(identityMatrix)

list1 = []
for i in range(50):
    list1.append(i * 0.75)
print(list1)

list2 = ([i * 0.75 for i in range(50)])
print(list2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.0, 0.75, 1.5, 2.25, 3.0, 3.75, 4.5, 5.25, 6.0, 6.75, 7.5, 8.25, 9.0, 9.75, 10.5, 11.25, 12.0, 12.75, 13.5, 14.25, 15.0, 15.75, 16.5, 17.25, 18.0, 18.75, 19.5, 20.25, 21.0, 21.75, 22.5, 23.25, 24.0, 24.75, 25.5, 26.25, 27.0, 27.75, 28.5, 29.25, 30.0, 30.75, 31.5, 32.25, 33.0, 33.75, 34.5, 35.25, 36.0, 36.75]
[0.0, 0.75, 1.5, 2.25, 3.0, 3.75, 4.5, 5.25, 6.0, 6.75, 7.5, 8.25, 9.0, 9.75, 10.5, 11.25, 12.0, 12.75, 13.5, 14.25, 15.0, 15.75, 16.5, 17.25, 18.0, 18.75, 19.5, 20.25, 21.0, 21.75, 22.5, 23.25, 24.0, 24.75, 25.5, 26.25, 27.0, 27.75, 28.5, 29.25, 30.0, 30.75, 31.5, 32.25, 33.0, 33.75, 34.5, 35.25, 36.0, 36.75]


Both the below scripts produces the multiples of 5 up to 50.

The For loop does not allow interactions between lists and integers. 

numpy.arange() allows us to perform operations over the array.

In [20]:
fiveTimesTable = [i * 5 for i in range(11)]
fiveTimesTable = np.arange(0, 55, 5)
print(f"0: {fiveTimesTable}")
print(f"1: {2 * fiveTimesTable}")
print(f"2: {10 + fiveTimesTable}")
print(f"3: {fiveTimesTable - 1}")
print(f"4: {fiveTimesTable / 5}")
print(f"5: {fiveTimesTable ** 2}")
print(f"6: {fiveTimesTable < 20}")
print(f"7: {fiveTimesTable[~(fiveTimesTable > 20)]}")

0: [ 0  5 10 15 20 25 30 35 40 45 50]
1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]
7: [ 0  5 10 15 20]
