# Tensors in Pytorch

PyTorch is based on tensors operations.<br>
A tensor can have different dimensions:
* 1-dimension - scalar
* 2-dimension - vector
* 3-dimension - matrix

In [1]:
import torch

Create a 2x2 array by creating a list of two lists, each of length two.

In [2]:
my_data = [[1,2], [3,4]]

Create a tensor in Pytorch by passing the data inside the Torch tensor constructor.

In [3]:
torch.tensor(my_data)

tensor([[1, 2],
        [3, 4]])

Torch defines 10 different tensor types with CPU and GPU varients, dependant on data type.<br>
We can access the tensor type use the attribute `dtype`.<br>

In [4]:
my_tensor = torch.tensor(my_data)
my_tensor.dtype

torch.int64

We can check this, we can use the `type` method.<br>
This will change if we are on GPU memory - On GPU memory, it is going to be a torch cuda LongTensor.

In [5]:
my_tensor.type()

'torch.LongTensor'

There are other dtypes available and the concept worth noting is Tensor Memory.

Tensors are defined as an array or matrix that contain data, which are allocated on a specific device.<br>
The two types of device are CPU and GPU.

On NumPy arrays exist on CPU memory only.<br>
With PyTorch, arrays can be allocated on the memory where you specify.<br>
By default, tensors are allocated to a CPU device as GPUs are not always available.<br>
We can check the device with the attribute `device`:

In [6]:
my_tensor.device

device(type='cpu')

Using a Google Colab environment allows the use of a free GPU.<br>
Using the below, we can allocate the tensor to the GPU:

In [7]:
# my_tensor.to('cuda')

After running the above, it shows `cuda:0`.<br>
This is the GPU id - the torch Tensor constructed with the cuda device.<br>
This is equivalent to `cuda:X` where X is the result of the `torch.cuda.current_device method`.<br>

To build a tensor from scratch build from zeroes or ones:

In [8]:
torch.zeros((2,2))

tensor([[0., 0.],
        [0., 0.]])

In [9]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

Starting a new tensor:

In [10]:
new_tensor = torch.ones((2,2))

In [11]:
new_tensor.dtype

torch.float32

In [12]:
new_tensor.type()

'torch.FloatTensor'

Creating a tensor from an existing tensor

In [13]:
new_tensor.new_tensor(my_data)

tensor([[1., 2.],
        [3., 4.]])

We still get a 2x2 matrix however instead of a int64 type, we have a float type.<br>
This tensor has hereditated the type of new_tensor from the tensor made from ones.

In [14]:
updated_tensor = new_tensor.new_tensor(my_data)
updated_tensor.dtype

torch.float32

Why would we want use the `new_tensor` method?

Tensors are arrays that contain data placed on CPU or GPU memory, and they have some properties.<br>
Sometimes you do not want to change those properties but you just want to hereditate such properties while updating the data.<br>
The new_tensor method allows us to reach this goal with a simple line of code.

The dtype is still float32, although new data is made of integers.<br>
However we can choose the dtype that we want inside the call:

In [15]:
another_tensor = torch.ones((2,2), dtype=torch.int8)

In [16]:
another_tensor

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

In [17]:
another_tensor.new_tensor(my_data)

tensor([[1, 2],
        [3, 4]], dtype=torch.int8)

We can also specify which device we want to allocate the tensor to:

In [18]:
# another_tensor = torch.ones((2,2), dtype=torch.int8, device='cuda')

In [19]:
# another_tensor.device

We can create tensors with similar types but different size:

In [20]:
new_data = [[1,2], [3,4], [5,6]]
another_tensor.new_tensor(new_data)

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int8)

This means we can create a new matrix with the same properties as the ones observerd in `another_tensor`.<br>
i.e. if allocated to cuda/GPU memory, assigned dtype, etc. it will use these same properties.

We can create a tensor with random values:

In [21]:
shape = (2,3,)
my_tensor = torch.rand(shape)

In [22]:
my_tensor

tensor([[0.3770, 0.0822, 0.1055],
        [0.4890, 0.6903, 0.2957]])

We can create new tensors directly from another tensor using the class of like operations.<br>
It will retain the properties (shape, datatype) of the argument tensor, unless overridden.<br>

In [23]:
torch.rand_like(my_tensor, dtype=torch.float)

tensor([[0.5747, 0.5365, 0.0239],
        [0.5085, 0.2002, 0.4224]])

We get a new tensor with the same shape as `my_tensor` but as we passed the dtype argument, it has changed accordingly.