# NumPy and Tensors
We can generate tensors from numpy arrays:

In [1]:
import numpy as np
numpy_data = np.random.rand(2,3)

In [2]:
numpy_data

array([[0.4157122 , 0.72006165, 0.55086637],
       [0.34399367, 0.49093253, 0.84534533]])

In [3]:
import torch
torch_numpy = torch.from_numpy(numpy_data)

In [4]:
torch_numpy

tensor([[0.4157, 0.7201, 0.5509],
        [0.3440, 0.4909, 0.8453]], dtype=torch.float64)

In [5]:
tensor_numpy_direct = torch.tensor(numpy_data)

In [6]:
tensor_numpy_direct

tensor([[0.4157, 0.7201, 0.5509],
        [0.3440, 0.4909, 0.8453]], dtype=torch.float64)

### Why would we do this?

We use a GPU to train a complex Machine learning model.<br>
Then we need to perform ex-post analysis on a local machine but do not have any GPUs.<br>
We can move the tensor from the GPU to a NumPy array with:

In [7]:
tensor_numpy_direct.cpu().numpy()

array([[0.4157122 , 0.72006165, 0.55086637],
       [0.34399367, 0.49093253, 0.84534533]])

The data is now in a NumPy array in CPU memory and can be used without the need for a GPU.

# Operations on Tensors
## Concatenating two+ tensors

In [8]:
numpy_data = np.random.rand(2,3)

In [9]:
numpy_data

array([[0.8294131 , 0.75838534, 0.68603296],
       [0.60578866, 0.95065312, 0.09848017]])

In [10]:
my_tns2 = torch.tensor(numpy_data)

In [11]:
my_tns2

tensor([[0.8294, 0.7584, 0.6860],
        [0.6058, 0.9507, 0.0985]], dtype=torch.float64)

In [12]:
my_tns1 = torch_numpy

In [13]:
my_tns1

tensor([[0.4157, 0.7201, 0.5509],
        [0.3440, 0.4909, 0.8453]], dtype=torch.float64)

We can concatenate with respect to the row dimension:

In [14]:
torch.cat([my_tns1, my_tns2], dim=0)

tensor([[0.4157, 0.7201, 0.5509],
        [0.3440, 0.4909, 0.8453],
        [0.8294, 0.7584, 0.6860],
        [0.6058, 0.9507, 0.0985]], dtype=torch.float64)

Or we can concatenate with respect to the column dimension:

In [15]:
torch.cat([my_tns1, my_tns2], dim=1)

tensor([[0.4157, 0.7201, 0.5509, 0.8294, 0.7584, 0.6860],
        [0.3440, 0.4909, 0.8453, 0.6058, 0.9507, 0.0985]], dtype=torch.float64)

We can clip the data if we wanted to apply a lower and upper bound to the generated data.<br>
Say for instance we believe there is an upper/lower bound in true data distribution.<br>
e.g. temperature in a location is bound by certain values.<br>
We can transform the data using `clip`, specifying the lower/upper bound:

In [16]:
my_tns2.clip(0.3,0.7)

tensor([[0.7000, 0.7000, 0.6860],
        [0.6058, 0.7000, 0.3000]], dtype=torch.float64)

## Element-wise Multiplication or Hadamard product

In [17]:
my_tns1.mul(my_tns2)

tensor([[0.3448, 0.5461, 0.3779],
        [0.2084, 0.4667, 0.0832]], dtype=torch.float64)

In [18]:
my_tns1 * my_tns2

tensor([[0.3448, 0.5461, 0.3779],
        [0.2084, 0.4667, 0.0832]], dtype=torch.float64)

## Matrix Multiplication

Matrix Multiplication can only be performed when their dimensions are compatible:

In [19]:
my_tns1.matmul(my_tns2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

As you can see the above error, we cannot multiply a matrix shape of 2x3 by itself.<br>
We have to multiply a 2x3 matrix by 3x2.<br>
Therefore, we need to **T**ranspose one matrix:

In [20]:
my_tns1.matmul(my_tns2.T)

tensor([[1.2688, 0.9906],
        [1.2376, 0.7583]], dtype=torch.float64)

In [21]:
my_tns1 @ my_tns2.T

tensor([[1.2688, 0.9906],
        [1.2376, 0.7583]], dtype=torch.float64)

A scalar tensor is a tensor made of one element.<br>
We can convert it to a Python value using the item method:

In [22]:
my_sum = my_tns2.sum()

In [23]:
my_sum

tensor(3.9288, dtype=torch.float64)

In [24]:
my_sum.item()

3.9287533619192505

In [25]:
type(my_sum.item())

float

We can create a grid of integers with PyTorch using `torch.arange()`:

In [26]:
torch.arange(20)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

Once we define this tensor, we can create a matrix using `reshape`:

In [27]:
matrix_A = torch.arange(20).reshape(5,4)

In [28]:
matrix_A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [29]:
matrix_B = matrix_A.clone()

In [30]:
matrix_B + matrix_A

tensor([[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22],
        [24, 26, 28, 30],
        [32, 34, 36, 38]])

In [31]:
matrix_B.mean()

RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

As per the above error, we specify the `dtype` to float:

In [32]:
matrix_A = torch.arange(20, dtype=torch.float32).reshape(5,4)

In [33]:
matrix_B = matrix_A.clone()

In [34]:
matrix_B.mean()

tensor(9.5000)

As default, the mean is computed on all values.<br>
We can however specify the dimension.<br>
To compute by column:

In [35]:
matrix_B.mean(dim=0)

tensor([ 8.,  9., 10., 11.])

In [36]:
matrix_B.sum(axis=0) / matrix_B.shape[0]

tensor([ 8.,  9., 10., 11.])